### ISSUE TITLE
NCAlgebra return strange thing when set a little letter variable with subscript

### ISSUE THREAD

**Issue by xlicz** [NCAlgebra/NC#1]
![return_strange_thing](https://cloud.githubusercontent.com/assets/4654912/24357788/5d33da26-1331-11e7-9e1e-d58e715a23db.png)
As shown in the pitcure.
The NCAlgebra version is development branch, commit 1fd0174.
The Mathematica version is 11.0.

**Comment by mcdeoliveira** [comment]
Hi xlicz, thanks for your report. Change the first two lines of your code to:

    SNC[p, R, q, t]
    SetCommutative[w]

and things will work.

Here's why: in this devel version of NCAlgebra we have completely revamped the core functions, including SNC and SetCommutative. In the past you could set pretty much anything to be NC at the expense of having a gigantic list of downvalue rules to test every time you ran any kind of calculation. In this newest version SNC uses upvalues instead, which only work for expressions of a certain depth. For this reason, I am currently restricting SNC to work only on symbols. I might change that in the future. On the other hand, the new core allows for things that are functions of NC variables to be treated as NC, which was not the case in the past. This makes subscript work by simply setting the base symbol to be nc. Try `FullForm` on a subscript expression to find out that your pretty symbol is really the expression `Subscript[p, i]`.

Please beware that some functionality might be lost with subscripts because of that. This is the case even in plain old MMA. For example, `a_Symbol + b -> {a,b}` would not match something like `Subscript[a,i] + 2` but would work fine with `a + 2`.

**Comment by mcdeoliveira** [comment]
The latest devel version has some more support for `Subscript`. Beware it is experimental at this stage, but already very usable.

**Comment by xlicz** [comment]
Hi, mcdeoliveira, I tried the last version of devel branch. It output different thing now, but the problem is still there, my mathematica notebook is as follow.
[subscript_problem.zip](https://github.com/NCAlgebra/NC/files/878024/subscript_problem.zip)

**Comment by mcdeoliveira** [comment]
Thanks for the reports. They were very useful!

Three issues:

1) There was an bug with the commutative variable w_i which was been thought as noncommutative. I have fixed this bug now. Please update your devel version. This was making your expression not valid since you used *. That's why you saw the `NotPolynomial` message. You should get a better message now in case it fails again.

2) A second issue is the warnings. As the warning warns... do not set a subscripted variable to be noncommutative. Set its base symbol instead. In your case this is what you should use:

        SNC[p, R, q, t]
        SetCommutative[w]

then any subscripted symbol, such as q_i or w_i, will be commutative or not based on the base symbol. Your entire code should look like:

    SNC[p, R, q, t]
    SetCommutative[w]
    expr = Subscript[w,i]*Subscript[w,i]*(tp[Subscript[p,i]-(R**Subscript[q,i]+t)]**(Subscript[p,i]-(R**Subscript[q,i]+t)))
    NCGrad[expr, t]

3) Please do not attach notebooks, specially on zipped files. This makes it impossible for someone later to follow the discussion without dowloading a file and unzipping it. Indent by 4 spaces and you will have your code formatted as above.

Thanks again for the bug reports!
